# Dependabot handles GitHub Actions (native integration, security alerts)
# Renovate handles Docker and Helm (better at complex versioning and pinning)
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps)
      include: scope
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /images/tools
    schedule:
      interval: daily
