repository:
  name: ghostwire
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  default_branch: main
