# TruffleHog configuration for Ghostwire
# https://github.com/trufflesecurity/trufflehog

# Note: TruffleHog v3 does not support allowlisting in YAML config
# Instead, use inline comments: # trufflehog:ignore
# Or exclude paths entirely with --exclude-paths flag
