version: '3'

env:
  VERSION:
    sh: grep '^version:' chart/Chart.yaml | awk '{print $2}'
  CHART_NAME:
    sh: grep '^name:' chart/Chart.yaml | awk '{print $2}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  test:
    desc: Run Helm tests (lint, template, unit tests)
    dir: chart
    cmds:
      - helm dependency update
      - helm lint .
      - helm template test . > /dev/null
      - echo "✅ Helm chart tests passed"

  schema:
    desc: Generate values.schema.json from values.yaml
    cmds:
      - ./scripts/generate-schema.sh

  package:
    desc: Package Helm chart locally for testing
    dir: chart
    cmds:
      - |
        echo "📦 Packaging Helm chart..."
        helm dependency update
        helm package . --destination /tmp
        echo "✅ Chart packaged: /tmp/{{.CHART_NAME}}-{{.VERSION}}.tgz"

  scan:
    desc: Run Trivy security scans (vulnerabilities, misconfigurations, secrets)
    cmds:
      - ./scripts/trivy-scan.sh

  changelog:
    desc: Generate CHANGELOG.md from git history using git-cliff
    cmds:
      - ./scripts/generate-changelog.sh
