version: '3'

dotenv: ['.env', '.env.local']

env:
  VERSION:
    sh: grep '^version:' chart/Chart.yaml | awk '{print $2}'
  CHART_NAME:
    sh: grep '^name:' chart/Chart.yaml | awk '{print $2}'
  REGISTRY: '{{.REGISTRY | default "ghcr.io"}}'
  NAMESPACE: '{{.NAMESPACE | default "drengskapur/ghostwire"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  claude:
    desc: Run Claude Code
    silent: true
    cmds:
      - claude --dangerously-skip-permissions --continue || claude --dangerously-skip-permissions

  resume:
    desc: Resume Claude Code session
    silent: true
    cmds:
      - claude --dangerously-skip-permissions --resume || claude --dangerously-skip-permissions

  test:
    desc: Run Helm tests (lint, template, unit tests)
    dir: chart
    cmds:
      - helm dependency update
      - helm lint .
      - helm template test . > /dev/null
      - echo "✅ Helm chart tests passed"

  schema:
    desc: Generate values.schema.json from values.yaml
    dir: chart
    cmds:
      - |
        echo "🔧 Generating Helm chart schema..."
        helm schema --no-additional-properties --indent 2

        echo "📝 Post-processing schema for flexibility..."
        # Fix overly restrictive schema for fields that need flexibility
        jq '
          # Allow arbitrary annotations and labels
          (.properties.podAnnotations | select(. != null)) |= del(.additionalProperties) |
          (.properties.podLabels | select(. != null)) |= del(.additionalProperties) |

          # Allow flexible ingress annotations
          (.properties.ingress.properties.annotations | select(. != null)) |= del(.additionalProperties) |

          # Allow flexible service account annotations
          (.properties.serviceAccount.properties.annotations | select(. != null)) |= del(.additionalProperties) |

          # Allow flexible arrays for extensibility
          (.properties.env | select(. != null)) |= del(.items.additionalProperties) |
          (.properties.envFrom | select(. != null)) |= del(.items.additionalProperties) |

          # Allow flexible node selector
          (.properties.nodeSelector | select(. != null)) |= del(.additionalProperties) |

          # Allow flexible tolerations
          (.properties.tolerations | select(. != null)) |= del(.items.additionalProperties) |

          # Allow flexible affinity rules
          (.properties.affinity | select(. != null)) |= del(.additionalProperties) |

          # Ensure imagePullSecrets are strings (secret names)
          (.properties.imagePullSecrets.items | select(. != null)) = { "type": "string" } |

          # Allow keycloak subchart to have its own schema - recursively remove additionalProperties
          (.properties."keycloak" | select(. != null)) |= walk(if type == "object" and has("additionalProperties") then del(.additionalProperties) else . end)
        ' values.schema.json > values.schema.json.tmp && mv values.schema.json.tmp values.schema.json

        echo "✅ Schema generated: values.schema.json"
        echo "💡 Your IDE can now provide validation and autocomplete for values.yaml"

  package:
    desc: Package Helm chart locally
    dir: chart
    cmds:
      - |
        echo "📦 Packaging Helm chart..."
        helm dependency update
        helm package . --destination /tmp
        echo "✅ Chart packaged: /tmp/{{.CHART_NAME}}-{{.VERSION}}.tgz"

  login:
    desc: Login to container registry
    silent: true
    cmds:
      - |
        if [ -z "$DOCKER_PASSWORD" ]; then
          echo "❌ DOCKER_PASSWORD not set"
          exit 1
        fi
        echo "$DOCKER_PASSWORD" | helm registry login {{.REGISTRY}} -u "$DOCKER_USERNAME" --password-stdin
        echo "✅ Logged in to {{.REGISTRY}}"

  helm:push:
    desc: Package and push Helm chart to OCI registry
    deps: [login]
    dir: chart
    cmds:
      - |
        echo "📦 Packaging Helm chart..."
        helm dependency update
        helm package . --destination /tmp

        PACKAGE_FILE="/tmp/{{.CHART_NAME}}-{{.VERSION}}.tgz"

        echo "📤 Pushing chart to OCI registry..."
        helm push "$PACKAGE_FILE" "oci://{{.REGISTRY}}/{{.NAMESPACE}}/charts"

        # Clean up package file
        rm -f "$PACKAGE_FILE"

        echo "✅ Helm chart pushed to oci://{{.REGISTRY}}/{{.NAMESPACE}}/charts/{{.CHART_NAME}}:{{.VERSION}}"

  helm:pull:
    desc: Pull Helm chart from OCI registry
    deps: [login]
    cmds:
      - |
        echo "📥 Pulling chart from OCI registry..."
        helm pull "oci://{{.REGISTRY}}/{{.NAMESPACE}}/charts/{{.CHART_NAME}}" \
          --version "{{.VERSION}}" \
          --destination /tmp

        echo "✅ Chart downloaded to /tmp/{{.CHART_NAME}}-{{.VERSION}}.tgz"

  changelog:
    desc: Generate CHANGELOG.md from git history using git-cliff
    silent: true
    cmds:
      - |
        if ! command -v git-cliff &> /dev/null; then
          echo "⚠️  git-cliff not found. Installing..."

          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)

          if [ "$ARCH" = "x86_64" ]; then
            ARCH="x86_64"
          elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            ARCH="aarch64"
          fi

          VERSION="2.10.1"
          URL="https://github.com/orhun/git-cliff/releases/download/v${VERSION}/git-cliff-${VERSION}-${ARCH}-unknown-${OS}-gnu.tar.gz"

          echo "📥 Downloading git-cliff ${VERSION}..."
          curl -sL "$URL" | sudo tar xz --strip-components=1 -C /usr/local/bin "git-cliff-${VERSION}/git-cliff"

          echo "✅ git-cliff installed to /usr/local/bin"
        fi

        echo "📝 Generating CHANGELOG.md..."
        git-cliff --output CHANGELOG.md
        echo "✅ CHANGELOG.md generated"
        echo ""
        echo "💡 Review: cat CHANGELOG.md"
