{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghostwire.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghostwire.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 1024

    defaults
        log global
        timeout client 3600s
        timeout connect 10s
        timeout server 3600s
        timeout tunnel 3600s
        mode http
        option httplog

    # VNC frontend - HTTP mode for WebSocket
    frontend vnc_frontend
        bind *:6901
        default_backend ghostwire_backend

    # Ghostwire backend - HTTP mode with WebSocket support
    backend ghostwire_backend
        mode http
        balance roundrobin
        option httpchk GET /
        # WebSocket support
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header X-Forwarded-For %[src]
        # Connect to ghostwire HTTPS endpoint
        server ghostwire1 {{ include "ghostwire.fullname" . }}:6901 ssl verify none check inter 10s rise 2 fall 3
{{- end }}
