{{- if .Values.tunnel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghostwire.fullname" . }}-cloudflared
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghostwire.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunnel
spec:
  replicas: {{ .Values.tunnel.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "ghostwire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tunnel
  template:
    metadata:
      labels:
        {{- include "ghostwire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tunnel
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cloudflared
        image: "{{ include "ghostwire.tunnelImage" . }}"
        imagePullPolicy: {{ .Values.tunnel.image.pullPolicy | default "IfNotPresent" }}
        args:
        - tunnel
        - --no-autoupdate
        - --metrics
        - 0.0.0.0:2000
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tunnel.secretName }}
              key: {{ .Values.tunnel.secretKey | default "token" }}
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.tunnel.resources | nindent 10 }}
{{- end }}
