{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghostwire.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghostwire.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  ports:
  - name: vnc
    port: 6901
    targetPort: 6901
    protocol: TCP
  selector:
    {{- include "ghostwire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
{{- end }}
