apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghostwire.fullname" . }}
  labels:
    {{- include "ghostwire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: vnc
      protocol: TCP
      name: vnc
  selector:
    {{- include "ghostwire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
