---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghostwire
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ghostwire
      version: '0.6.0'
      sourceRef:
        kind: HelmRepository
        name: ghcr
        namespace: flux-system
  releaseName: ghostwire
  targetNamespace: ghostwire
  install:
    createNamespace: true
    timeout: 15m
  upgrade:
    timeout: 15m
    force: true
    cleanupOnFail: true
  values:
    # Local k3d environment - optimized for development
    image:
      repository: kasmweb/signal
      tag: "1.18.0"
      pullPolicy: IfNotPresent

    # Service configuration for k3d
    service:
      type: NodePort
      port: 6901
      targetPort: 6901

    # Disable ingress (using NodePort instead)
    ingress:
      enabled: false

    # Persistent storage for Signal data
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 2Gi  # Minimal size for dev environment

    # Reduced resources for local development
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi

    # Environment configuration
    env:
      - name: VNC_PW
        value: "password"
      - name: VNC_RESOLUTION
        value: "1280x720"

    # Authentication with Keycloak
    # Keycloak provides full IAM with proper web UI for user management
    # NOTE: Keycloak is NOT protecting VNC access - for future OAuth integration
    auth:
      enabled: true

    # Cloudflare Tunnel configuration
    tunnel:
      enabled: true
      replicaCount: 1
      image:
        repository: cloudflare/cloudflared
        tag: "2025.10.0"
      secretName: cloudflared-credentials
      secretKey: token
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

    # HAProxy configuration for efficient VNC/WebSocket handling
    haproxy:
      enabled: true
      replicaCount: 1
      image:
        repository: haproxytech/haproxy-alpine
        tag: "2.9"
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 32Mi

