---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghostwire
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ghostwire
      version: '0.5.0'
      sourceRef:
        kind: HelmRepository
        name: ghcr
        namespace: flux-system
  releaseName: ghostwire
  targetNamespace: ghostwire
  install:
    createNamespace: true
    timeout: 15m
  upgrade:
    timeout: 15m
    force: true
    cleanupOnFail: true
  values:
    # Local k3d environment - optimized for development
    image:
      repository: kasmweb/signal
      tag: "1.18.0"
      pullPolicy: IfNotPresent

    # Service configuration for k3d
    service:
      type: NodePort
      port: 6901
      targetPort: 6901

    # Disable ingress (using NodePort instead)
    ingress:
      enabled: false

    # Persistent storage for Signal data
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 2Gi  # Minimal size for dev environment

    # Reduced resources for local development
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi

    # Environment configuration
    env:
      - name: VNC_PW
        value: "password"
      - name: VNC_RESOLUTION
        value: "1280x720"
      - name: VNCOPTIONS
        value: "-PreferBandwidth -DynamicQualityMin=4 -DynamicQualityMax=7 -DLP_ClipDelay=0 -disableBasicAuth"

    # Authentication with OAuth2 Proxy
    auth:
      enabled: true

    # OAuth2 Proxy configuration
    oauth2-proxy:
      image:
        repository: "quay.io/oauth2-proxy/oauth2-proxy"
        tag: "v7.12.0"
        pullPolicy: IfNotPresent

      config:
        clientID: "htpasswd"
        clientSecret: "htpasswd"
        # Generate with: openssl rand -base64 32 | head -c 32 | base64
        cookieSecret: "NlREUUVYVlV0Q2UzdmNjZ1ppRGN2dz09"
        cookieName: "_oauth2_proxy_ghostwire"
        cookieExpire: "8h"
        cookieRefresh: "1h"
        cookieSecure: false  # HTTP for local dev
        cookieHttpOnly: true
        # Configuration file for htpasswd authentication
        configFile: |-
          # Upstream to HAProxy which handles VNC/WebSocket efficiently
          upstreams = [ "http://ghostwire-haproxy.ghostwire.svc.cluster.local:6901/" ]

          # WebSocket support (CRITICAL for VNC streaming)
          proxy_websockets = true
          pass_host_header = true
          pass_access_token = false
          pass_user_headers = false
          pass_authorization_header = false
          set_xauthrequest = false
          set_authorization_header = false

          # Display htpasswd login form (disables OAuth providers)
          display_htpasswd_form = true
          skip_provider_button = true

          # Cookie configuration
          cookie_expire = "8h0m0s"
          cookie_refresh = "1h0m0s"
          cookie_secure = false
          cookie_httponly = true

          # Email domain configuration
          email_domains = [ "*" ]

          # Logging configuration
          standard_logging = true
          auth_logging = true
          request_logging = true
          silence_ping_logging = true

      htpasswdFile:
        enabled: true
        entries:
          - admin:$2y$05$6pLmHJVVs.kRz8cT/Ki5xuHPCWLLjCCC8qBKm.xM3nK1P/xhDZMCa  # admin:password

      service:
        type: ClusterIP
        portNumber: 4180

      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

    # Cloudflare Tunnel configuration
    tunnel:
      enabled: true
      replicaCount: 1
      image:
        repository: cloudflare/cloudflared
        tag: "2025.10.0"
      secretName: cloudflared-credentials
      secretKey: token
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

    # HAProxy configuration for efficient VNC/WebSocket handling
    haproxy:
      enabled: true
      replicaCount: 1
      image:
        repository: haproxytech/haproxy-alpine
        tag: "2.9"
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 32Mi

