version: '3'

dotenv: ['../.env', '../.env.local']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Setup FluxCD GitOps for k3d-ghostwire development cluster
    cmds:
      - ./scripts/setup-flux.sh

  cluster:
    desc: Create k3d cluster from config
    cmds:
      - k3d cluster create --config k3d-config.yaml

  destroy:
    desc: Delete k3d-ghostwire cluster
    cmds:
      - k3d cluster delete ghostwire

  tunnel:
    desc: Setup Cloudflare Tunnel for ghostwire-dev.adhoc-solutions.com (automated)
    cmds:
      - ./scripts/setup-tunnel.sh
