name: Auto-Merge Bot PRs

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-Merge Bot PRs
    runs-on: ubuntu-latest
    if: |
      (github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]') &&
      github.event.pull_request.state == 'open'
    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --auto \
            --squash \
            --delete-branch
