name: Security Scanning

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # For commenting on PRs
  security-events: write # For uploading SARIF results

jobs:
  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0 # Full history for comprehensive scanning

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@fd007c74a0603e5e9c66cdc1c1dec6ce1e2bc05d # main
        with:
          # Scan the entire repository
          path: ./
          extra_args: --debug --only-verified

  trivy-repo:
    name: Trivy Repository Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@b6643a29c2ef6e1b78c1916f9c7b619fc3ab3f9b # master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          skip-files: '.trufflehog.yaml'

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    # Only run on PRs (not needed for push to main)
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@455294851b49b8f84a6baa6abdd5a22f16f2f729 # v4
        with:
          fail-on-severity: high
          # Allow licenses: Apache-2.0, MIT, BSD-3-Clause
          allow-licenses: Apache-2.0, MIT, BSD-2-Clause, BSD-3-Clause, ISC

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [trufflehog, trivy-repo]
    if: always()
    steps:
      - name: Check scan results
        run: |
          echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- TruffleHog: ${{ needs.trufflehog.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Trivy: ${{ needs.trivy-repo.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.trufflehog.result }}" == "failure" ]] || \
             [[ "${{ needs.trivy-repo.result }}" == "failure" ]]; then
            echo "⚠️ **One or more security scans failed. Review the logs above.**" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "✅ **All security scans passed.**" >> $GITHUB_STEP_SUMMARY
          fi
